### ISSUE TITLE
Habeas corpus des blogs pété ?

### ISSUE THREAD

**Issue by thibnton** [mdiplo/habeascorpus#6]
On dirait bien que le bloc de suggestions au bas des billets de blogs est pété 
Cf. https://blog.mondediplo.net/ecrire/?exec=article&id_article=1943

<img width="1029" alt="capture d ecran 2018-06-05 a 16 00 57" src="https://user-images.githubusercontent.com/12396835/41042677-8bf1cc10-69a2-11e8-98c6-b8d74ee780aa.png">

**Comment by Fil** [comment]
en quoi est-ce pêté exactement ? les suggestions sont un peu ratées, mais l'article parle de de gaulle et les suggestions aussi ; testé sur un autre article, j'avais des réponses plus ou moins en rapport (ça parlait de théâtre)

Sinon, le truc fait appel au grand compute donc il faut plutôt solliciter @BoOz ;)

**Comment by thibnton** [comment]
Là pour le coup je crois qu'il est vraiment pété https://blog.mondediplo.net/ecrire/?exec=article_edit&id_article=1954
<img width="927" alt="capture d ecran 2018-08-30 a 16 33 41" src="https://user-images.githubusercontent.com/12396835/44858602-acca7a00-ac72-11e8-9d94-e7215f701ba7.png">

Alors qu'il devrait donner ceci (quand je passe par diploïser) 
<img width="1249" alt="capture d ecran 2018-08-30 a 16 35 29" src="https://user-images.githubusercontent.com/12396835/44858643-be138680-ac72-11e8-8a32-f56088b1975d.png">

C'est plus toi que je dois assigner à ce genre de missions, @Fil ?

**Comment by Fil** [comment]
Comme je dis plus haut, ce plugin utilise "grand compute", œuvre de Maître @BoOz. La partie qui me concerne fonctionne vu ce que tu décris :)

**Comment by thibnton** [comment]
J'ai géré de pas te réassigner du coup. PARDON.

**Comment by Fil** [comment]
Ça va y’a pas 💀

**Comment by Fil** [comment]
![Capture d’écran 2019-05-23 à 23 02 26](https://user-images.githubusercontent.com/7001/58286355-ddc57e80-7dae-11e9-8d5c-6833fb6f823f.png)

💪

**Comment by lewer** [comment]
Félicitations !

Le jeu. 23 mai 2019 à 23:02, Philippe Rivière <notifications@github.com> a
écrit :

**Comment by thibnton** [comment]
bravo et merci

>
